#!/usr/bin/python3
import os, sys, shutil, zipfile, tarfile
from pathlib import Path

flatpak = os.path.exists("/.flatpak-info")
snap = os.environ.get('SNAP_NAME', '') == 'savedesktop'

# native directory
native_dir = "~/.local/share/savedesktop/src"

# Cache directory
cache_path = f"{Path.home()}/.var/app/io.github.vikdevelop/SaveDesktop/cache/tmp" if flatpak else f"{os.getenv('SNAP_USER_COMMON')}/.cache/tmp" if snap else f"{Path.home()}/.cache/io.github.vikdevelop.SaveDesktop"

# Init dir for loading the Python scripts
sys.path.append("/app" if flatpak else f"{os.getenv('SNAP')}/usr" if snap else native_dir)

if len(sys.argv) < 2:
    import main_window
else:
    command = sys.argv[1]
    if command in "--background":
       import periodic_saving
    elif command == "--sync":
        import network_sharing
    elif command == "--save-now":
        os.system("python3 /app/periodic_saving.py --now" if flatpak else f"python3 {snap}/usr/periodic_saving.py --now" if snap else "python3 ~/.local/share/savedesktop/src/periodic_saving.py --now")
    elif command == "--import-config":
        if len(sys.argv) < 3:
            print("Please provide a file path for --import-config")
            sys.exit(1)
        
        file_path = sys.argv[2]
        shutil.rmtree(os.path.join(cache_path, "import_config"), ignore_errors=True)
        os.makedirs(os.path.join(cache_path, "import_config"), exist_ok=True)
        os.chdir(os.path.join(cache_path, "import_config"))

        if file_path.endswith('.sd.zip'):
            os.system(f"unzip {file_path}")
        elif file_path.endswith('.sd.tar.gz'):
            tarfile.open(file_path).extractall()
        else:
            print("Unsupported file type. Use *.sd.tar.gz or *.sd.zip.")
            sys.exit()
        
        from config import Import
        Import()
    elif command == "--help":
        print('\033[1mArguments:\033[0m \n'
      ' None | Run SaveDesktop app (GUI) \n'
      ' --background | Start periodic saving \n'
      ' --sync | Sync desktop configuration \n'
      ' --import-config /path/to/filename.sd.tar.gz or /path/to/filename.sd.zip | Import configuration \n'
      ' --save-now | Save configuration using UI parameters\n'
      ' --help | Show this message')
    else:
        print("Unknown command. Use --help for more information.")
