name: savedesktop
grade: stable
adopt-info: savedesktop
license: GPL-3.0+
icon: flatpak/icons/io.github.vikdevelop.SaveDesktop.svg
base: core24
confinement: strict

plugs:
  dot-config:
    interface: personal-files
    write:
      - $HOME/.config
  dot-local:
    interface: personal-files
    write:
      - $HOME/.local
  dot-themes:
    interface: personal-files
    write:
      - $HOME/.themes
  dot-icons:
    interface: personal-files
    write:
      - $HOME/.icons
  dot-fonts:
    interface: personal-files
    write:
      - $HOME/.fonts
  #DE specific
  dot-xfce4:
    interface: personal-files
    write:
      - $HOME/.xfce4
  dot-cinnamon:
    interface: personal-files
    write:
      - $HOME/.cinnamon

platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [arm64]
  armhf:
    build-on: [armhf]

layout:
  /usr/share/gvfs:
    bind: $SNAP/usr/share/gvfs
  /usr/lib/7zip:
    bind: $SNAP/usr/lib/7zip

apps:
  savedesktop:
    extensions: [gnome]
    command: usr/bin/savedesktop
    desktop: usr/share/applications/io.github.vikdevelop.SaveDesktop.desktop
    common-id: io.github.vikdevelop.SaveDesktop.desktop
    plugs:
      - home
      - network
      - login-session-control

parts:
  dconf:
    source: https://gitlab.gnome.org/GNOME/dconf.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dbash_completion=false
      - -Dman=false
      - -Dvapi=false
    prime:
      - -usr/lib/systemd
      - -usr/lib/*/pkgconfig
      - -usr/include

  savedesktop:
    source: https://github.com/vikdevelop/SaveDesktop.git
    plugin: meson
    source-tag: '3.7-beta'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/savedesktop/current/usr
    organize:
      snap/savedesktop/current/usr: usr
    parse-info: [ usr/share/metainfo/io.github.vikdevelop.SaveDesktop.metainfo.xml ]
    override-build: |
      craftctl default
      sed -i '1s|#!/snap/gnome-46-2404-sdk/current/usr/bin/python3|#!/usr/bin/env python3|' $CRAFT_PART_INSTALL/usr/bin/savedesktop

  deps:
    after: [ dconf, savedesktop ]
    plugin: nil
    stage-packages:
      - libnotify-bin
      - p7zip-full
      - coreutils
    stage:
      - usr/bin/notify-send
      - usr/bin/7z
      - usr/lib/7zip/7z
      - usr/lib/7zip/7z.so
