name: Bug report
description: Report a bug of SaveDesktop app to developer
title: "bug:"
labels: [bug]
body:
  - type: input
    id: distro
    attributes:
      label: Linux distribution
      description: "What Linux distribution (name and version) are you using?"
      placeholder: "e.g. Fedora 40, Ubuntu 24.04"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Desktop Environment
      description: |
        What desktop environment are you using?
      options:
        - Select
        - GNOME
        - KDE Plasma
        - Xfce
        - Cinnamon
        - MATE
        - Pantheon (elementaryOS)
        - Budgie
        - COSMIC
        - Deepin
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version of the SaveDesktop app
      description: "You can find it by clicking on the three dots in the header bar and then the 'About app' button."
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package type
      description: |
        How did you install SaveDesktop?
      options:
        - Flatpak from Flathub
        - Flatpak, which was built with Flatpak Builder
        - Native from this repository
        - Snap from Snap Store
        - Other
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Bug description
      description: Describe the problem, steps to reproduce, alternatively insert output from the terminal
    validations:
      required: true
