name: Bug report
description: Report a bug with Save Desktop
title: "bug: "
labels: [bug]
body:
  - type: input
    id: distro
    attributes:
      label: "Linux distribution"
      description: "What Linux distribution (name and version) are you using?"
      placeholder: "e.g. Fedora 40, Ubuntu 24.04"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: "Desktop Environment"
      description: "What desktop environment are you using?"
      options:
        - (please select)
        - GNOME
        - KDE Plasma
        - Xfce
        - Cinnamon
        - MATE
        - Pantheon (elementaryOS)
        - Budgie
        - COSMIC
        - Deepin
        - Hyprland
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Version of the Save Desktop app"
      description: "You can find it by clicking on the three dots in the header bar and then the 'About app' button."
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: "Package type"
      description: "How did you install Save Desktop?"
      options:
        - (please select)
        - Flatpak from Flathub
        - GNOME Builder
        - Other (please specify in the bug description)
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: "Bug description"
      description: "Briefly describe the problem"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Describe how you came across the problem"
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: "Output from the Terminal"
      description: "Open the Terminal app (Ctrl+Alt+T or find it in the apps' menu) and run the flatpak run io.github.vikdevelop.SaveDesktop command (alternatively, add another argument if you run in CLI). Then insert the output below. Please insert full output as text, not a screenshot!"
    validations:
      required: true
