name: Question
description: Ask a question about how Save Desktop works
title: "question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: |
        Ask about how Save Desktop works or how to use a specific feature.
        Please check the README and existing issues first.
    validations:
      required: true

  - type: input
    id: context
    attributes:
      label: Context (optional)
      description: |
        Linux distribution, desktop environment, or usage scenario.
    validations:
      required: false